-- MakanMie Analytics database
-- Run this entire file in Supabase > SQL Editor.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','whatsapp_click','menu_click')),
  page text not null default '/',
  visitor_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at);
create index if not exists analytics_events_event_type_idx on public.analytics_events(event_type);
create index if not exists analytics_events_visitor_id_idx on public.analytics_events(visitor_id);

alter table public.analytics_events enable row level security;

-- Visitors may insert analytics events. They cannot read analytics.
drop policy if exists "Anyone can record analytics" on public.analytics_events;
create policy "Anyone can record analytics"
on public.analytics_events for insert
to anon, authenticated
with check (
  event_type in ('page_view','whatsapp_click','menu_click')
  and length(visitor_id) between 10 and 100
  and length(page) between 1 and 500
);

-- Admins can read analytics after logging in.
drop policy if exists "Authenticated admins can read analytics" on public.analytics_events;
create policy "Authenticated admins can read analytics"
on public.analytics_events for select
to authenticated
using (true);
